services:
  # The restserver and joex containers defined here are configured
  # using env variables. Both must connect to the same database and
  # solr instance. More information on configuring can be found here:
  # https://docspell.org/docs/configure
  #
  # Please replace the values of the following with a custom secret
  # string:
  #
  # - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET
  # - DOCSPELL_SERVER_AUTH_SERVER__SECRET
  # - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE
  #   (use the same value at the consumedir container!)
  #
  # After creating an account, you may want to set signup mode to
  # "closed" or to "invite". When using invite, you must also set
  # DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD to some
  # secret.
  restserver:
    image: docspell/restserver:latest
    container_name: docspell-restserver
    restart: unless-stopped
    ports:
      - "7880:7880"
    environment:
      - TZ=${TZ}
      - DOCSPELL_SERVER_INTERNAL__URL=http://docspell-restserver:7880
      - DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET=HE%&A%6WQ&x4
      - DOCSPELL_SERVER_AUTH_SERVER__SECRET=82521451fcf32d0d30a43e2a7468d604
      - DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD=izJEdSj4)Gb}=2Pr
      - DOCSPELL_SERVER_BACKEND_JDBC_URL=jdbc:postgresql://db:5432/docspell
      - DOCSPELL_SERVER_BACKEND_JDBC_USER=docspell
      - DOCSPELL_SERVER_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr:8983/solr/docspell
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_ENABLED=true
      - DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE=9311b16295f6a26f420d1f69c5e7a50e
      - DOCSPELL_SERVER_BACKEND_SIGNUP_MODE=open
      - DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD=
      - DOCSPELL_SERVER_BACKEND_ADDONS_ENABLED=false
    labels:
      traefik.enable: true
      traefik.http.routers.restserver.rule: Host(`docspell.${DOMAIN}`)
      traefik.http.routers.restserver.entrypoints: websecure
      traefik.http.routers.restserver.tls: true
      traefik.http.routers.restserver.tls.certresolver: letsencrypt
      traefik.http.services.restserver.loadbalancer.server.port: 7880
      traefik.port: 7880
    networks:
      - web
      - docspell
    depends_on:
      - solr
      - db

  joex:
    image: docspell/joex:latest
    container_name: docspell-joex
    ## For more memory add corresponding arguments, like below. Also see
    ## https://docspell.org/docs/configure/#jvm-options
    # command:
    #   - -J-Xmx3G
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - DOCSPELL_JOEX_APP__ID=joex1
      - DOCSPELL_JOEX_PERIODIC__SCHEDULER_NAME=joex1
      - DOCSPELL_JOEX_SCHEDULER_NAME=joex1
      - DOCSPELL_JOEX_BASE__URL=http://docspell-joex:7878
      - DOCSPELL_JOEX_BIND_ADDRESS=0.0.0.0
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_ENABLED=true
      - DOCSPELL_JOEX_FULL__TEXT__SEARCH_SOLR_URL=http://docspell-solr:8983/solr/docspell
      - DOCSPELL_JOEX_JDBC_PASSWORD=izJEdSj4)Gb}=2Pr
      - DOCSPELL_JOEX_JDBC_URL=jdbc:postgresql://db:5432/docspell
      - DOCSPELL_JOEX_JDBC_USER=docspell
      - DOCSPELL_JOEX_ADDONS_EXECUTOR__CONFIG_RUNNER=docker,trivial
      - DOCSPELL_JOEX_CONVERT_HTML__CONVERTER=weasyprint
    ports:
      - "7878:7878"
    networks:
      - docspell
    depends_on:
      - solr
      - db
    ## Uncomment when using the "docker" runner with addons
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp

  # The consumedir container watches a directory for files to upload
  # to docspell restserver. This uses the `dsc` tool. For information
  # on the available options, see `dsc --help`.
  # https://github.com/docspell/dsc
  #
  # The value after `Docspell-Integration` must match the secret
  # specified at the restserver via
  # DOCSPELL_SERVER_INTEGRATION__ENDPOINT_HTTP__HEADER_HEADER__VALUE.
  #
  # The --not-matches "**/.*" option is to exclude hidden files.
  consumedir:
    image: docspell/dsc:latest
    container_name: docspell-consumedir
    command:
      - dsc
      - "-d"
      - "http://docspell-restserver:7880"
      - "watch"
      - "--delete"
      - "-ir"
      - "--not-matches"
      - "**/.*"
      - "--header"
      - "Docspell-Integration:9311b16295f6a26f420d1f69c5e7a50e"
      - "/opt/docs"
    restart: unless-stopped
    volumes:
      - /f/_shared/docs:/opt/docs
    networks:
      - docspell
    depends_on:
      - restserver

  db:
    image: postgres:15.3
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - ${DOCKER_DATA_DIR}/docspell/postgres:/var/lib/postgresql/data/
    networks:
      - docspell
    environment:
      - POSTGRES_USER=docspell
      - POSTGRES_PASSWORD=izJEdSj4)Gb}=2Pr
      - POSTGRES_DB=docspell

  solr:
    image: solr:9
    container_name: docspell-solr
    restart: unless-stopped
    volumes:
      - ${DOCKER_DATA_DIR}/docspell/solr:/var/solr
    networks:
      - docspell
    command:
      - bash
      - -c
      - 'precreate-core docspell; exec solr -f -Dsolr.modules=analysis-extras'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983/solr/docspell/admin/ping"]
      interval: 1m
      timeout: 10s
      retries: 2
      start_period: 30s

networks:
  web:
    name: traefik_web
    external: true
  docspell:
    name: docspell