services:
  jellyfin_courses:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin_courses
    #runtime: nvidia # Expose NVIDIA GPUs
    #network_mode: host # Enable DLNA and Wake-on-Lan
    ports:
      - ${JELLYFIN_COURSES_HTTP_PORT}:8096 # HTTP port
      - ${JELLYFIN_COURSES_HTTPS_PORT}:8920 # HTTPS port
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 6G
        reservations:
          cpus: '1'
          memory: 4G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin_courses.rule: Host(`courses.${DOMAIN}`)
      traefik.http.routers.jellyfin_courses.entrypoints: websecure
      traefik.http.routers.jellyfin_courses.tls: true
      traefik.http.routers.jellyfin_courses.tls.certresolver: letsencrypt
      traefik.http.services.jellyfin_courses.loadbalancer.server.port: 8096
      traefik.port: 8096
    volumes:
      - ${DOCKER_DATA_DIR}/jellyfin_courses/config:/config
      - ${DOCKER_DATA_DIR}/jellyfin_courses/cache:/cache
      - /f/backup/jellyfin_courses:/mnt/backup # Backup directory
      - /e/courses:/mnt/courses # Media directory
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    name: traefik_web
    external: true