version: "3"

services:
  sabnzbd:
    image: linuxserver/sabnzbd:4.1.0
    container_name: sabnzbd
    labels:
      traefik.enable: true
      traefik.http.routers.sabnzbd.rule: Host(`nzb.${DOMAIN}`)
      traefik.http.routers.sabnzbd.entrypoints: websecure
      traefik.http.routers.sabnzbd.tls: true
      traefik.http.routers.sabnzbd.tls.certresolver: letsencrypt
      traefik.http.services.sabnzbd.loadbalancer.server.port: 8080
      traefik.port: 8080
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - ${SABNZBD_HTTP_PORT}:8080
    volumes:
      - '${DOCKER_DATA_DIR}/sabnzbd:/config'
      - '/f/downloads/incomplete:/incomplete-downloads'
      - '/f/downloads/complete:/downloads/complete'
      - '/f/downloads/watch:/downloads/watch'
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    name: traefik_web