version: "3"

services:
  vaultwarden:
    image: vaultwarden/server:1.27.0
    container_name: vaultwarden
    ports:
      - ${VAULTWARDEN_HTTP_PORT}:80
    labels:
      traefik.enable: true
      traefik.http.routers.vaultwarden.rule: Host(`6e48d67113cb48e9767902313f73cea5.${DOMAIN}`) || Host(`warden.${DOMAIN}`)
      traefik.http.routers.vaultwarden.entrypoints: websecure
      traefik.http.routers.vaultwarden.tls: true
      traefik.http.routers.vaultwarden.tls.certresolver: letsencrypt
      traefik.http.services.vaultwarden.loadbalancer.server.port: 80
      traefik.port: 80
    volumes:
      - ${DOCKER_DATA_DIR}/vaultwarden:/data/
    networks:
      - web
    restart: unless-stopped
    
networks:
  web:
    name: traefik_web
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24