services:
  emby:
    image: emby/embyserver:4.8.8.0
    container_name: emby
    #runtime: nvidia # Expose NVIDIA GPUs
    #network_mode: host # Enable DLNA and Wake-on-Lan
    ports:
      - ${EMBY_HTTP_PORT}:8096 # HTTP port
      - ${EMBY_HTTPS_PORT}:8920 # HTTPS port
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 6G
        reservations:
          cpus: '1'
          memory: 1G
          # devices:
          #   - driver: nvidia
          #     count: 1
          #     capabilities: [gpu]
    labels:
      traefik.enable: true
      traefik.http.routers.emby.entrypoints: websecure
      traefik.http.routers.emby.tls: true
      traefik.http.routers.emby.tls.certresolver: letsencrypt
      traefik.http.services.emby.loadbalancer.server.port: 8096
      traefik.http.middlewares.emby-https-redirect.redirectscheme.scheme: https
      traefik.port: 8096
    volumes:
      - ${DOCKER_DATA_DIR}/emby-4.8/config:/config
      # - ${DOCKER_DATA_DIR}/emby/themes:/system/dashboard-ui/modules/themes
      - /f/backup/emby:/mnt/backup # Backup directory
      - /e/movies:/mnt/movies # Media directory
      - /d/shows:/mnt/shows # Media directory
      - /d/anime:/mnt/anime # Media directory
      - /d/audio_books:/mnt/audio_books # Media directory
    #devices:
    #  - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    #  - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    name: traefik_web
    external: true