version: "3.3"

services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: "cloudflare-ddns"
    environment:
      - API_KEY=AskVh21xlQsQWDh_VpkqDTANWfHlW72lJEVYnHPP
      - ZONE=fae.sh
      - CRON=*/5 * * * *
    restart: unless-stopped
  
  traefik:
    image: traefik:v2.8
    container_name: "traefik"
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`traefik.fae.sh`) # Define the subdomain for the traefik dashboard.
      traefik.http.routers.traefik.entrypoints: websecure       # Set the Traefik entry point.
      traefik.http.routers.api.service: api@internal            # Enable Traefik API.
      # traefik.http.middlewares.admin-auth.basicauth.users: kazuto:$$2y$$10$$kZJcpW4wVIdkJzWGfHQLGu.r1MZef6bb98f/RRW9ANHN.G9zPkZuO
      # traefik.http.routers.traefik.middlewares: admin-auth@docker
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /f/docker/compose/network/:/etc/traefik/
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /f/docker/data/letsencrypt/:/letsencrypt
    networks:
      - web
    restart: unless-stopped

  pihole:
    image: pihole/pihole:2022.07.1
    container_name: pihole
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: HE%&A%6WQ&x4
    labels:
      traefik.enable: true
      traefik.http.routers.pihole.rule: Host(`f2482f7878ecee30c686f1c5ee09d76e.fae.sh`)
      traefik.http.routers.pihole.entrypoints: websecure
      traefik.http.routers.pihole.tls: true
      traefik.http.routers.pihole.tls.certresolver: letsencrypt
      traefik.http.services.pihole.loadbalancer.server.port: 80
      traefik.port: 80
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "1337:80/tcp"
    volumes:
      - '/f/docker/data/pihole/pihole:/etc/pihole'
      - '/f/docker/data/pihole/dnsmasq:/etc/dnsmasq.d'    
    networks:
      - web
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:2.15.1
    container_name: portainer
    environment:
      TZ: 'Europe/Berlin'
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.rule: Host(`80d0dd0e0b023e6f976d188c53351968.fae.sh`)
      traefik.http.routers.portainer.entrypoints: websecure
      traefik.http.routers.portainer.tls: true
      traefik.http.routers.portainer.tls.certresolver: letsencrypt
      traefik.http.services.portainer.loadbalancer.server.port: 9000
      traefik.port: 9000
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /f/docker/data/portainer/:/data
    networks:
      - web
    restart: unless-stopped

  heimdall:
    image: linuxserver/heimdall:2.4.13
    container_name: heimdall
    ports:
      - 8082:80
      - 4434:443
    labels:
      traefik.enable: true
      traefik.http.routers.heimdall.rule: Host(`3594131de4c77a189a6ac09d15ef828a.fae.sh`) || Host(`heimdall.fae.sh`)
      traefik.http.routers.heimdall.entrypoints: websecure
      traefik.http.routers.heimdall.tls: true
      traefik.http.routers.heimdall.tls.certresolver: letsencrypt
      traefik.http.services.heimdall.loadbalancer.server.port: 80
      traefik.port: 80
    volumes:
      - /f/docker/data/heimdall:/config
    networks:
      - web
    restart: unless-stopped

  vaultwarden:
    image: vaultwarden/server:1.27.0
    container_name: vaultwarden
    ports:
      - 8083:80
    labels:
      traefik.enable: true
      traefik.http.routers.vaultwarden.rule: Host(`6e48d67113cb48e9767902313f73cea5.fae.sh`) || Host(`warden.fae.sh`)
      traefik.http.routers.vaultwarden.entrypoints: websecure
      traefik.http.routers.vaultwarden.tls: true
      traefik.http.routers.vaultwarden.tls.certresolver: letsencrypt
      traefik.http.services.vaultwarden.loadbalancer.server.port: 80
      traefik.port: 80
    volumes:
      - /f/docker/data/vaultwarden:/data/
    networks:
      - web
    restart: unless-stopped
    
networks:
  web:
    name: traefik_web
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24