version: "3.3"

services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    container_name: "cloudflare-ddns"
    environment:
      - API_KEY=AskVh21xlQsQWDh_VpkqDTANWfHlW72lJEVYnHPP
      - ZONE=kazu.pw
      - CRON=*/5 * * * *
    restart: unless-stopped

  traefik:
    image: traefik:v2.8
    container_name: "traefik"
    command:
      - "--api.insecure=true" 
      - "--providers.docker"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=traefik_web"

      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certResolver=le"
      - "--serverstransport.insecureskipverify=true"

      - "--entrypoints.web.forwardedHeaders.insecure=true"
      - "--entryPoints.web.forwardedHeaders.trustedIPs=127.0.0.1/32,172.23.0.1"
      - "--entrypoints.websecure.forwardedHeaders.insecure=true"
      - "--entryPoints.websecure.forwardedHeaders.trustedIPs=127.0.0.1/32,172.23.0.1"
      
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=kai@mayer.ws"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"

      - "--entrypoints.tcp.address=:9090"

      - "--experimental.plugins.traefik-real-ip.modulename=github.com/soulbalz/traefik-real-ip"
      - "--experimental.plugins.traefik-real-ip.version=v1.0.3"
      #- "--accesslog=true"
      #- "--log.level=DEBUG"
      #- "--tracing=true"
    # labels:
      # - "traefik.enable=true"
      # - "traefik.port=8080"
      # - "traefik.http.middlewares.basic-auth.basicauth.users=mayer:$$apr1$$xvowjsh9$$TqCL90XEs9nF6HcsEgyKu/"
      # - "traefik.http.middlewares.admin-auth.basicauth.users=kazuto:$$2y$$10$$Pq8Yni4RFYzvUHcYjBt0fePoSsQYFmNP5q5oS35h4xFgrLsbZNJaW"
      # - "traefik.http.routers.traefik.rule=Host(`traefik.kazu.pw`)"
      # - "traefik.http.routers.traefik.entrypoints=websecure"
      # - "traefik.http.routers.traefik.tls=true"
      # - "traefik.http.routers.traefik.tls.certresolver=le"
      # - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      # - "traefik.http.routers.traefik.middlewares=admin-auth@docker"
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 9090
        published: 9090
        mode: host
      - target: 8080
        published: 8080
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /e/homelab/letsencrypt/:/letsencrypt
    networks:
      - web
    restart: unless-stopped

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.kazu.pw`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=le"
      - "traefik.http.middlewares.forwardauth.forwardauth.tls.insecureSkipVerify=true"
      - "traefik.http.middlewares.forwardauth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.forwardauth.forwardauth.address=https://whoami.kazu.pw"
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    name: traefik_web