version: '2'

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:27.1.1
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 8G
    labels:
      traefik.enable: true
      traefik.http.routers.nextcloud.rule: Host(`cloud.${DOMAIN}`)
      traefik.http.routers.nextcloud.entrypoints: websecure
      traefik.http.routers.nextcloud.tls: true
      traefik.http.routers.nextcloud.tls.certresolver: letsencrypt
      traefik.http.services.nextcloud.loadbalancer.server.port: 80
      traefik.port: 80
      traefik.http.middlewares.nextcloud_redirect.redirectregex.permanent: true
      traefik.http.middlewares.nextcloud_redirect.redirectregex.regex: https://(.*)/.well-known/(?:card|cal)dav
      traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement: https://$${1}/remote.php/dav
      traefik.http.routers.nextcloud.middlewares: nextcloud_redirect
    ports:
      - 8081:80
    links:
      - postgres
      - redis
    volumes:
      - ${DOCKER_DATA_DIR}/nextcloud:/var/www/html
    environment:
      - REDIS_HOST=redis
      - TRUSTED_PROXIES=192.168.90.0/24
    networks:
      - web
      - nextcloud
    restart: unless-stopped

networks:
  web:
    name: traefik_web
  nextcloud:
    name: nextcloud_web
