version: '2'

services:
  postgres:
    container_name: postgres
    image: postgres:15.1
    ports:
      - 5432:5432
    volumes:
      - /f/docker/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=@A25D6n#N^&fe#agGG47s5!i
    networks:
      - web
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:7.0.8
    ports:
      - 6379:6379
    networks:
      - web
    restart: unless-stopped

  nextcloud:
    container_name: nextcloud
    image: nextcloud:27.1.1
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 8G
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`5f40b17473d19a3d763ad2925b4c6014.fae.sh`) || Host(`cloud.fae.sh`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=le"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.port=80"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=https://$${1}/remote.php/dav"
      - "traefik.http.middlewares.nextcloud_secure_headers.headers.accessControlMaxAge=100"
      - "traefik.http.middlewares.nextcloud_secure_headers.headers.hostsProxyHeaders=X-Forwarded-Host"
      - "traefik.http.middlewares.nextcloud_secure_headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.nextcloud_secure_headers.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.nextcloud_secure_headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud_secure_headers.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud_secure_headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.nextcloud_secure_headers.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.nextcloud_secure_headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.nextcloud_secure_headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.nextcloud_secure_headers.headers.referrerPolicy=same-origin"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud_redirect,nextcloud_secure_headers"
    ports:
      - 8081:80
    links:
      - postgres
      - redis
    volumes:
      - /f/docker/data/nextcloud:/var/www/html
    environment:
      - REDIS_HOST=redis
      - TRUSTED_PROXIES=192.168.90.0/24
    networks:
      - web
      - nextcloud
    restart: unless-stopped

networks:
  web:
    name: traefik_web
  nextcloud:
    name: nextcloud_web
