services:
  rocketchat:
    container_name: rocketchat
    image: rocketchat/rocket.chat:latest
    labels:
      traefik.enable: true
      traefik.http.routers.rocketchat.rule: Host(`chat.${DOMAIN}`)
      traefik.http.routers.rocketchat.entrypoints: websecure
      traefik.http.routers.rocketchat.tls: true
      traefik.http.routers.rocketchat.tls.certresolver: letsencrypt
      traefik.http.services.rocketchat.loadbalancer.server.port: 3000
      traefik.port: 3000
    ports:
      - ${ROCKET_CHAT_HTTP_PORT}:3000
    environment:
      MONGO_URL: "mongodb://mongodb:27017/rocketchat?replicaSet=rs0"
      MONGO_OPLOG_URL: "mongodb://mongodb:27017/local?replicaSet=rs0"
      ROOT_URL: https://chat.${DOMAIN}
      PORT: 3000
      DEPLOY_METHOD: docker
    depends_on:
      - mongodb
    networks:
      - web
    restart: unless-stopped

  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:5.0
    volumes:
      - ${DOCKER_DATA_DIR}/rocketchat/database:/bitnami/mongodb
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_PORT_NUMBER: 27017
      MONGODB_INITIAL_PRIMARY_HOST: mongodb
      MONGODB_INITIAL_PRIMARY_PORT_NUMBER: 27017
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ENABLE_JOURNAL: true
      ALLOW_EMPTY_PASSWORD: yes
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    name: traefik_web
    external: true
