version: "3.3"

services:
  portainer:
    image: portainer/portainer-ce:2.15.1
    container_name: portainer
    environment:
      TZ: 'Europe/Berlin'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`80d0dd0e0b023e6f976d188c53351968.kazu.pw`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=le"
      - "traefik.http.services.portainer.loadbalancer.server.port=9443"
      - "traefik.port=9443"
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /e/homelab/portainer/:/data
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    name: traefik_web