services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    environment:
      EULA: "TRUE"
      TYPE: "CURSEFORGE"
      CF_SERVER_MOD: "/modpacks/CMA+Server+Files+0.4.2.zip"
      # CF_SERVER_MOD: "/modpacks/ATM7SKY-1.0.4.zip"
      #TYPE: "FTBA"
      #FTB_MODPACK_ID: 95
      #FTB_MODPACK_VERSION_ID: 2239
    labels:
      traefik.enable: true
      traefik.tcp.routers.minecraft.rule: HostSNI(`mc.${DOMAIN}`)
      traefik.tcp.routers.minecraft.entrypoints: tcp
      traefik.port: 25565
    ports:
      - ${MINECRAFT_TCP_PORT}:25565
    volumes:
      - '${DOCKER_DATA_DIR}/minecraft/cma:/data'
      - '${DOCKER_DATA_DIR}/minecraft/modpacks:/modpacks'
    tty: true
    stdin_open: true
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    name: traefik_web
    external: true