version: "3.3"

services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    environment:
      EULA: "TRUE"
      TYPE: "CURSEFORGE"
      # VERSION: 1.18.2
      # FORGEVERSION: 40.1.74
      CF_SERVER_MOD: "/modpacks/ATM7SKY-1.0.4.zip"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.minecraft.rule=HostSNI(`mc.kazu.pw`)"
      - "traefik.tcp.routers.minecraft.entrypoints=tcp"
      - "traefik.tcp.routers.minecraft.tls=true"
      - "traefik.tcp.routers.minecraft.tls.certresolver=le"
      - "traefik.tcp.services.minecraft.loadbalancer.server.port=25565"
      - "traefik.port=25565"
    ports:
      - 25565:25565
    volumes:
      - '/e/homelab/minecraft/atm7sky:/data'
      - '/e/homelab/minecraft/modpacks:/modpacks'
    tty: true
    stdin_open: true
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    name: traefik_web