services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      # CF_SERVER_MOD: "/modpacks/Craftoria-Server-1.6.1.zip"
      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/all-the-mods-10
      CF_API_KEY: ${CF_API_KEY}
      MEMORY: 10G
    labels:
      traefik.enable: true
      traefik.tcp.routers.minecraft.rule: HostSNI(`mc.${DOMAIN}`)
      traefik.tcp.routers.minecraft.entrypoints: tcp
      traefik.port: 25565
    ports:
      - ${MINECRAFT_TCP_PORT}:25565
    volumes:
      - '${DOCKER_DATA_DIR}/minecraft/atm10:/data'
      - '${DOCKER_DATA_DIR}/minecraft/modpacks:/modpacks'
    tty: true
    stdin_open: true
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    name: traefik_web
    external: true